import React,{useState,useEffect,useRef} from 'react';
import {ArrowUp,Mic,Square,Volume2,Plus,ArrowUpRight,Check,Database,MessageSquare,ShieldCheck,Phone,PhoneCall,PhoneOff,VolumeX,Radio,Waves} from 'lucide-react';
import {newSession,respond,toTicket} from '../services/aiService.js';
import {redactSensitive} from '../services/security.js';
import {scenarios} from '../data/oracleErrors.js';
import {Badge,PageTitle,Safety} from '../components/UI.jsx';
export default function Consultation({onTicket,onDashboard}){
 const [session,setSession]=useState(newSession),[input,setInput]=useState(''),[customer,setCustomer]=useState('Demo Customer A'),[version,setVersion]=useState('Oracle Database 19c'),[busy,setBusy]=useState(false),[voice,setVoice]=useState(false),[listening,setListening]=useState(false),[notice,setNotice]=useState(''),[phoneOpen,setPhoneOpen]=useState(false),[callStatus,setCallStatus]=useState('대기 중'),[callSeconds,setCallSeconds]=useState(0),[muted,setMuted]=useState(false),[phoneStep,setPhoneStep]=useState(0),[callListening,setCallListening]=useState(false),[callTranscript,setCallTranscript]=useState(''),[callMessage,setCallMessage]=useState('마이크 버튼을 눌러 고객의 음성을 받아보세요.');
 const recognition=useRef(null),phoneRecognition=useRef(null),end=useRef(null),lock=useRef(false),callTimer=useRef(null);
 const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[session,busy]);
 useEffect(()=>()=>{recognition.current?.abort();phoneRecognition.current?.abort();window.speechSynthesis?.cancel();clearTimeout(callTimer.current)},[]);
 useEffect(()=>{if(!phoneOpen||callStatus!=='연결됨')return;const timer=setInterval(()=>setCallSeconds(v=>v+1),1000);return()=>clearInterval(timer)},[phoneOpen,callStatus]);
 function speak(text){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text.replace(/ORA-(\d{5})/g,'오라 $1'));utterance.lang='ko-KR';utterance.rate=.98;window.speechSynthesis.speak(utterance)}
 async function send(value=input,{speakReply=false}={}){if(!value.trim()||lock.current||session.done)return;const safe=redactSensitive(value);lock.current=true;setBusy(true);setInput('');setNotice(safe.matched.length?`${safe.matched.join(', ')} 정보는 자동으로 마스킹했습니다.`:'');
  try{const next=await respond(session,safe.text);setSession(next);if(next.done)onTicket(toTicket(next,customer,version));if((voice||speakReply)&&window.speechSynthesis)speak(next.messages.at(-1).text);return next}finally{setBusy(false);lock.current=false}
 }
 function mic(){if(!SR){setNotice('현재 브라우저에서는 음성 인식을 지원하지 않습니다. 텍스트로 문의해주세요.');return}if(listening){recognition.current?.stop();return}const r=new SR();recognition.current=r;r.lang='ko-KR';r.interimResults=false;r.onresult=e=>setInput(v=>(v+' '+e.results[0][0].transcript).trim());r.onerror=e=>{setNotice(e.error==='not-allowed'?'마이크 권한이 필요합니다. 브라우저 권한을 허용하거나 텍스트로 문의해주세요.':'음성을 인식하지 못했습니다. 다시 시도하거나 텍스트로 문의해주세요.');setListening(false)};r.onend=()=>setListening(false);try{r.start();setListening(true)}catch{setNotice('마이크를 시작할 수 없습니다. 텍스트로 문의해주세요.')}}
 function reset(){recognition.current?.abort();phoneRecognition.current?.abort();window.speechSynthesis?.cancel();setSession(newSession());setInput('');setNotice('')}
 function startPhoneDemo(){if(session.rule&&!session.done){setNotice('진행 중인 상담이 있습니다. 새 상담 후 전화 데모를 시작해주세요.');return}if(session.done){setNotice('상담이 완료되었습니다. 새 상담을 시작한 뒤 전화 데모를 실행해주세요.');return}setPhoneOpen(true);setMuted(false);setPhoneStep(0);setCallTranscript('');setCallMessage('연결 후 고객의 문의를 음성으로 받아 적습니다.');setCallSeconds(0);setCallStatus('연결 중');clearTimeout(callTimer.current);callTimer.current=setTimeout(async()=>{setCallStatus('연결됨');const next=await send('DB 접속이 안되고 ORA-12514 오류가 발생합니다.',{speakReply:true});setCallMessage(next?.messages.at(-1)?.text||'고객의 응답을 기다리고 있습니다.')},850)}
 async function phoneReply(text){if(callStatus!=='연결됨'||busy)return;await send(text);setPhoneStep(v=>v+1)}
 function startCallListening(){if(!SR){setCallMessage('이 브라우저는 음성 인식을 지원하지 않습니다. 아래 빠른 응답을 사용하거나 텍스트 상담으로 진행해주세요.');return}if(muted){setCallMessage('음소거를 해제한 뒤 고객 음성을 받아보세요.');return}if(callListening){phoneRecognition.current?.stop();return}const r=new SR();phoneRecognition.current=r;r.lang='ko-KR';r.interimResults=true;r.continuous=false;r.onstart=()=>{setCallListening(true);setCallMessage('고객 음성을 듣고 있습니다…')};r.onresult=e=>{const text=Array.from(e.results).map(result=>result[0].transcript).join(' ').trim();setCallTranscript(text);const last=e.results[e.results.length-1];if(last.isFinal&&text){setCallMessage('AI가 내용을 분석하고 있습니다…');send(text,{speakReply:true}).then(next=>{setPhoneStep(v=>v+1);setCallMessage(next?.done?'상담 요약을 엔지니어 Dashboard로 등록했습니다.':next?.messages.at(-1)?.text||'다음 정보를 확인해주세요.')})}};r.onerror=e=>{setCallMessage(e.error==='not-allowed'?'마이크 권한이 필요합니다. 브라우저 권한을 허용한 뒤 다시 시도해주세요.':'음성을 인식하지 못했습니다. 다시 말하거나 빠른 응답을 사용해주세요.');setCallListening(false)};r.onend=()=>setCallListening(false);try{r.start()}catch{setCallMessage('마이크를 시작할 수 없습니다. 다시 시도해주세요.')}}
 function endPhoneDemo(){clearTimeout(callTimer.current);phoneRecognition.current?.abort();window.speechSynthesis?.cancel();setCallListening(false);setPhoneOpen(false);setCallStatus('대기 중')}
 const time=`${String(Math.floor(callSeconds/60)).padStart(2,'0')}:${String(callSeconds%60).padStart(2,'0')}`;
 const phoneReplies=['PROD 입니다.','Listener는 정상입니다.','OPEN입니다.'];
 const stage=session.done?4:session.rule?2:0;
 return <><PageTitle eyebrow="CUSTOMER SUPPORT" title="AI 상담" description="문제는 간단히 말씀해주세요. 필요한 정보는 AI가 차근차근 확인합니다."><div className="consult-actions"><button className="button call-button" onClick={startPhoneDemo}><PhoneCall size={16}/>전화 데모</button><button className="button secondary" onClick={reset}><Plus size={16}/>새 상담</button></div></PageTitle>
 <div className="consult-grid"><section className="panel chat-panel"><div className="chat-top"><div className="agent-icon"><Database size={22}/></div><div><h2>DB Care AI</h2><span>AI DB Support Agent</span></div><Badge type="green"><i/>AI 상담원 연결됨</Badge></div>
 <div className="progress">{['문의 접수','증상 확인','환경 정보 수집','AI 분석','엔지니어 이관'].map((s,i)=><div key={s} className={i<=stage?'active':''}><span>{i<stage?<Check size={11}/>:i+1}</span>{s}</div>)}</div>
 <div className="messages" role="log" aria-live="polite">{session.messages.map((m,i)=><div key={i} className={`message ${m.role}`}><div className="message-label">{m.role==='assistant'?'DB CARE AI':'고객'}</div><div className="bubble">{m.text}</div></div>)}{session.done&&<div className="handoff"><Check size={20}/><div><strong>엔지니어에게 전달할 준비가 끝났습니다</strong><p>문의가 Dashboard에 등록되었습니다.</p></div><button onClick={onDashboard} aria-label="Dashboard에서 확인"><ArrowUpRight size={20}/></button></div>}<div ref={end}/></div>
 <div className="composer-wrap">{notice&&<p className="notice" role="status">{notice}</p>}<form className="composer" onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="문의 내용" rows="2" value={input} onChange={e=>setInput(e.target.value)} disabled={session.done||busy} placeholder={session.done?'상담이 완료되었습니다. 새 상담을 시작해보세요.':'증상이나 ORA 오류 코드를 입력해주세요…'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="composer-actions"><button type="button" className={listening?'icon-button recording':'icon-button'} disabled={session.done} aria-label={listening?'음성 입력 중지':'마이크 음성 입력'} onClick={mic}>{listening?<Square size={17}/>:<Mic size={18}/>}</button><span>{listening?'듣고 있습니다…':'Enter 전송 · Shift+Enter 줄바꿈'}</span><button type="submit" className="send" disabled={!input.trim()||session.done||busy} aria-label="메시지 전송"><ArrowUp size={19}/></button></div></form><div className="composer-footer"><span>비밀번호와 개인정보는 입력하지 마세요.</span><button className={voice?'text-button enabled':'text-button'} onClick={()=>{setVoice(!voice);if(voice)window.speechSynthesis?.cancel()}} disabled={!window.speechSynthesis}><Volume2 size={14}/>답변 읽기 {voice?'ON':'OFF'}</button></div></div></section>
 <aside className="context-column"><section className="panel context-card"><div className="section-kicker">CONSULTATION CONTEXT</div><h2>상담 환경</h2><label>고객사명<input value={customer} onChange={e=>setCustomer(e.target.value)} disabled={!!session.rule}/></label><label>DB Version<select value={version} onChange={e=>setVersion(e.target.value)} disabled={!!session.rule}>{['Oracle Database 19c','Oracle Database 21c','Oracle Database 23ai','기타 / 확인 필요'].map(v=><option key={v}>{v}</option>)}</select></label><div className="context-status"><span>문의 유형</span><strong>{session.rule?.category||'분류 대기'}</strong><span>긴급도</span><Badge type={session.priority==='높음'?'red':'neutral'}>{session.rule?session.priority:'—'}</Badge></div></section>
 <section className="panel phone-card"><div className="phone-card-title"><span className="section-kicker">VOICE CALL DEMO</span><Radio size={15}/></div><h2>전화 상담을 체험해보세요.</h2><p>가상의 고객 전화를 받아 AI가 필요한 정보를 수집하고 이관합니다.</p><button className="phone-start" onClick={startPhoneDemo}><PhoneCall size={17}/>전화 데모 시작</button><small>실제 통화, 녹음, 전화망 연결은 없습니다.</small></section>
 <section className="panel scenario-card"><div className="section-kicker">TRY THE DEMO</div><h2>어떤 문제가 발생했나요?</h2><p>시나리오를 선택해 상담을 시작해보세요.</p>{scenarios.map(([code,name,text])=><button className="scenario" key={code} disabled={!!session.rule||busy} onClick={()=>send(text)}><span><strong>{name}</strong><small>{code}</small></span><ArrowUpRight size={17}/></button>)}</section>
 <div className="mock-note"><ShieldCheck size={19}/><div><strong>안전한 데모 환경</strong><p>Rule 기반 Mock AI로 동작합니다.<br/>실제 DB 연결 및 명령 실행은 없습니다.</p></div></div></aside></div><Safety/>
 {phoneOpen&&<div className="phone-overlay" role="dialog" aria-modal="true" aria-labelledby="phone-demo-title"><div className="phone-modal"><header><div><span className="section-kicker">BROWSER VOICE CALL</span><h2 id="phone-demo-title">Demo Customer A</h2><p>{callStatus==='연결 중'?'AI 상담원에게 연결하고 있습니다…':callStatus}</p></div><button className="icon-button" onClick={endPhoneDemo} aria-label="전화 데모 닫기">×</button></header><div className="call-orb"><Waves size={44}/><span className={callStatus==='연결됨'?'pulse':''}/></div><strong className="call-time">{callStatus==='연결됨'?time:'--:--'}</strong><p className="call-caption">{callStatus==='연결됨'?'마이크로 고객 응답을 받고 AI가 음성으로 다음 질문을 안내합니다.':'통화 세션을 준비하고 있습니다.'}</p><div className="call-flow"><div className="call-flow-item active"><span>01</span><div><strong>고객 문의 접수</strong><small>ORA-12514 · DB 접속 장애</small></div></div><div className={phoneStep>0?'call-flow-item active':'call-flow-item'}><span>02</span><div><strong>필수 정보 수집</strong><small>SERVICE_NAME · Listener · DB 상태</small></div></div><div className={session.done?'call-flow-item active':'call-flow-item'}><span>03</span><div><strong>엔지니어 이관</strong><small>자동 요약과 함께 Dashboard 등록</small></div></div></div>{callStatus==='연결됨'&&!session.done&&<div className="voice-console"><span>LIVE VOICE TRANSCRIPT</span><p className={callTranscript?'':'placeholder'}>{callTranscript||callMessage}</p><button className={callListening?'voice-capture active':'voice-capture'} onClick={startCallListening} disabled={busy||muted}><Mic size={18}/>{callListening?'듣는 중 · 탭하여 종료':'고객 음성 받기'}</button><div className="phone-script"><span>마이크를 쓸 수 없을 때</span><button onClick={()=>phoneReply(phoneReplies[phoneStep]||'확인 불가')} disabled={busy}>{phoneReplies[phoneStep]||'확인 불가'}</button></div></div>}{session.done&&<div className="phone-complete"><Check size={17}/>상담 요약이 Dashboard에 등록되었습니다.</div>}<div className="call-controls"><button className={muted?'muted':''} onClick={()=>{setMuted(v=>!v);if(!muted)phoneRecognition.current?.stop()}} aria-label={muted?'음소거 해제':'음소거'}>{muted?<VolumeX size={18}/>:<Mic size={18}/>}<span>{muted?'음소거 해제':'음소거'}</span></button><button className="hangup" onClick={endPhoneDemo} aria-label="전화 종료"><PhoneOff size={19}/><span>통화 종료</span></button></div><small className="call-privacy">브라우저 음성 인식을 사용하며, 음성 파일을 저장하거나 외부 전화망에 연결하지 않습니다.</small></div></div>}</>;
}

