import React,{useState,useEffect,useRef} from 'react';
import {ArrowUp,Mic,Square,Volume2,Plus,ArrowUpRight,Check,Database,MessageSquare,ShieldCheck} from 'lucide-react';
import {newSession,respond,toTicket} from '../services/aiService.js';
import {scenarios} from '../data/oracleErrors.js';
import {Badge,PageTitle,Safety} from '../components/UI.jsx';
export default function Consultation({onTicket,onDashboard}){
 const [session,setSession]=useState(newSession),[input,setInput]=useState(''),[customer,setCustomer]=useState('Demo Customer A'),[version,setVersion]=useState('Oracle Database 19c'),[busy,setBusy]=useState(false),[voice,setVoice]=useState(false),[listening,setListening]=useState(false),[notice,setNotice]=useState('');
 const recognition=useRef(null),end=useRef(null),lock=useRef(false);
 const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[session,busy]);
 useEffect(()=>()=>{recognition.current?.abort();window.speechSynthesis?.cancel()},[]);
 async function send(value=input){if(!value.trim()||lock.current||session.done)return;lock.current=true;setBusy(true);setInput('');setNotice('');
  try{const next=await respond(session,value);setSession(next);if(next.done)onTicket(toTicket(next,customer,version));if(voice&&window.speechSynthesis){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(next.messages.at(-1).text);utterance.lang='ko-KR';window.speechSynthesis.speak(utterance)}}finally{setBusy(false);lock.current=false}
 }
 function mic(){if(!SR){setNotice('현재 브라우저에서는 음성 인식을 지원하지 않습니다. 텍스트로 문의해주세요.');return}if(listening){recognition.current?.stop();return}const r=new SR();recognition.current=r;r.lang='ko-KR';r.interimResults=false;r.onresult=e=>setInput(v=>(v+' '+e.results[0][0].transcript).trim());r.onerror=e=>{setNotice(e.error==='not-allowed'?'마이크 권한이 필요합니다. 브라우저 권한을 허용하거나 텍스트로 문의해주세요.':'음성을 인식하지 못했습니다. 다시 시도하거나 텍스트로 문의해주세요.');setListening(false)};r.onend=()=>setListening(false);try{r.start();setListening(true)}catch{setNotice('마이크를 시작할 수 없습니다. 텍스트로 문의해주세요.')}}
 function reset(){recognition.current?.abort();window.speechSynthesis?.cancel();setSession(newSession());setInput('');setNotice('')}
 const stage=session.done?4:session.rule?2:0;
 return <><PageTitle eyebrow="CUSTOMER SUPPORT" title="AI 상담" description="문제는 간단히 말씀해주세요. 필요한 정보는 AI가 차근차근 확인합니다."><button className="button secondary" onClick={reset}><Plus size={16}/>새 상담</button></PageTitle>
 <div className="consult-grid"><section className="panel chat-panel"><div className="chat-top"><div className="agent-icon"><Database size={22}/></div><div><h2>DB Care AI</h2><span>AI DB Support Agent</span></div><Badge type="green"><i/>AI 상담원 연결됨</Badge></div>
 <div className="progress">{['문의 접수','증상 확인','환경 정보 수집','AI 분석','엔지니어 이관'].map((s,i)=><div key={s} className={i<=stage?'active':''}><span>{i<stage?<Check size={11}/>:i+1}</span>{s}</div>)}</div>
 <div className="messages" role="log" aria-live="polite">{session.messages.map((m,i)=><div key={i} className={`message ${m.role}`}><div className="message-label">{m.role==='assistant'?'DB CARE AI':'고객'}</div><div className="bubble">{m.text}</div></div>)}{session.done&&<div className="handoff"><Check size={20}/><div><strong>엔지니어에게 전달할 준비가 끝났습니다</strong><p>문의가 Dashboard에 등록되었습니다.</p></div><button onClick={onDashboard} aria-label="Dashboard에서 확인"><ArrowUpRight size={20}/></button></div>}<div ref={end}/></div>
 <div className="composer-wrap">{notice&&<p className="notice" role="status">{notice}</p>}<form className="composer" onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="문의 내용" rows="2" value={input} onChange={e=>setInput(e.target.value)} disabled={session.done||busy} placeholder={session.done?'상담이 완료되었습니다. 새 상담을 시작해보세요.':'증상이나 ORA 오류 코드를 입력해주세요…'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="composer-actions"><button type="button" className={listening?'icon-button recording':'icon-button'} disabled={session.done} aria-label={listening?'음성 입력 중지':'마이크 음성 입력'} onClick={mic}>{listening?<Square size={17}/>:<Mic size={18}/>}</button><span>{listening?'듣고 있습니다…':'Enter 전송 · Shift+Enter 줄바꿈'}</span><button type="submit" className="send" disabled={!input.trim()||session.done||busy} aria-label="메시지 전송"><ArrowUp size={19}/></button></div></form><div className="composer-footer"><span>비밀번호와 개인정보는 입력하지 마세요.</span><button className={voice?'text-button enabled':'text-button'} onClick={()=>{setVoice(!voice);if(voice)window.speechSynthesis?.cancel()}} disabled={!window.speechSynthesis}><Volume2 size={14}/>답변 읽기 {voice?'ON':'OFF'}</button></div></div></section>
 <aside className="context-column"><section className="panel context-card"><div className="section-kicker">CONSULTATION CONTEXT</div><h2>상담 환경</h2><label>고객사명<input value={customer} onChange={e=>setCustomer(e.target.value)} disabled={!!session.rule}/></label><label>DB Version<select value={version} onChange={e=>setVersion(e.target.value)} disabled={!!session.rule}>{['Oracle Database 19c','Oracle Database 21c','Oracle Database 23ai','기타 / 확인 필요'].map(v=><option key={v}>{v}</option>)}</select></label><div className="context-status"><span>문의 유형</span><strong>{session.rule?.category||'분류 대기'}</strong><span>긴급도</span><Badge type={session.priority==='높음'?'red':'neutral'}>{session.rule?session.priority:'—'}</Badge></div></section>
 <section className="panel scenario-card"><div className="section-kicker">TRY THE DEMO</div><h2>어떤 문제가 발생했나요?</h2><p>시나리오를 선택해 상담을 시작해보세요.</p>{scenarios.map(([code,name,text])=><button className="scenario" key={code} disabled={!!session.rule||busy} onClick={()=>send(text)}><span><strong>{name}</strong><small>{code}</small></span><ArrowUpRight size={17}/></button>)}</section>
 <div className="mock-note"><ShieldCheck size={19}/><div><strong>안전한 데모 환경</strong><p>Rule 기반 Mock AI로 동작합니다.<br/>실제 DB 연결 및 명령 실행은 없습니다.</p></div></div></aside></div><Safety/></>;
}

