import React,{useState,useEffect,useRef} from 'react';
import {Inbox,Clock,ClipboardCheck,CheckCircle2,Search,ArrowUpRight,X,Download} from 'lucide-react';
import {Badge,PageTitle,Safety} from '../components/UI.jsx';
const statuses=['접수 대기','엔지니어 확인 필요','처리 완료'];
export default function Dashboard({tickets,onUpdate}){
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('전체 상태'),[selected,setSelected]=useState(null);const ticket=tickets.find(t=>t.id===selected);
 const today=new Date().toDateString();const metrics=[['오늘 접수',tickets.filter(t=>new Date(t.createdAt).toDateString()===today).length,Inbox,'오늘의 고객 문의'],['접수 대기',tickets.filter(t=>t.status===statuses[0]).length,Clock,'검토를 기다리는 문의'],['엔지니어 확인 필요',tickets.filter(t=>t.status===statuses[1]).length,ClipboardCheck,'전문가의 확인이 필요해요'],['처리 완료',tickets.filter(t=>t.status===statuses[2]).length,CheckCircle2,'지원이 완료된 문의']];
 const filtered=tickets.filter(t=>(filter==='전체 상태'||t.status===filter)&&`${t.customer} ${t.category} ${t.code}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageTitle eyebrow="ENGINEER WORKSPACE" title="문의 Dashboard" description="AI가 수집한 정보를 한눈에 확인하고, 다음 조치에 집중하세요."><Badge type="green"><i/>브라우저 로컬 저장</Badge></PageTitle>
 <div className="metrics">{metrics.map(([title,n,Icon,caption],i)=><div className={`panel metric metric-${i}`} key={title}><div><span>{title}</span><Icon size={18}/></div><strong>{String(n).padStart(2,'0')}</strong><small>{caption}</small></div>)}</div>
 <section className="panel ticket-panel"><div className="table-heading"><div><h2>고객 문의 <span className="count">{tickets.length}</span></h2><p>접수된 문의와 AI 상담 요약을 확인합니다.</p></div><span className="tiny-label">LIVE IN THIS BROWSER</span></div><div className="filters"><div className="search"><Search size={17}/><input aria-label="문의 검색" placeholder="고객사, 오류 코드, 문의 유형 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="상태 필터" value={filter} onChange={e=>setFilter(e.target.value)}>{['전체 상태',...statuses].map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="table-scroll"><table><thead><tr>{['접수시간','고객사','문의 유형','오류 코드','DB Version','긴급도','상태',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{filtered.map(t=><tr key={t.id} onClick={()=>setSelected(t.id)}><td><strong>{new Date(t.createdAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false})}</strong><small>{new Date(t.createdAt).toLocaleDateString('ko-KR',{month:'2-digit',day:'2-digit'})}</small></td><td><button className="row-link" onClick={()=>setSelected(t.id)}>{t.customer}</button><small>{t.sample?'샘플 문의':'AI 상담 접수'}</small></td><td>{t.category}</td><td><code>{t.code}</code></td><td className="muted">{t.version.replace('Database ','')}</td><td><Badge type={t.priority==='높음'?'red':'neutral'}>{t.priority}</Badge></td><td><Badge type={t.status==='처리 완료'?'green':t.status==='접수 대기'?'neutral':'amber'}>{t.status}</Badge></td><td><ArrowUpRight size={16}/></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty"><Inbox size={30}/><h3>표시할 문의가 없습니다</h3><p>검색 조건을 바꾸거나 AI 상담에서 새 문의를 접수하세요.</p></div>}</div><div className="table-foot">총 {filtered.length}건 표시<span>문의 행을 선택하면 상세 내용을 볼 수 있습니다.</span></div></section>
 <div className="dashboard-bottom"><div><span className="section-kicker">FROM CONVERSATION TO ACTION</span><h3>반복 질문은 AI에게, 문제 해결은 엔지니어에게.</h3><p>문의 원문부터 환경 정보까지, 상담 맥락을 놓치지 않고 이어갑니다.</p></div><div className="flow-mini"><span>문의 접수</span>→<span>AI 정보 수집</span>→<strong>엔지니어 검토</strong></div></div><Safety/>
 {ticket&&<Detail ticket={ticket} onClose={()=>setSelected(null)} onUpdate={onUpdate}/>}</>;
}
function Detail({ticket:t,onClose,onUpdate}){
 const dialog=useRef(null);const [note,setNote]=useState(t.note),[saved,setSaved]=useState(false);
 useEffect(()=>{dialog.current.showModal();const d=dialog.current;return()=>d.close()},[]);
 function download(){const text=[`DB Care AI 상담 요약`,t.customer,t.category,t.code,t.version,`상태: ${t.status}`,`긴급도: ${t.priority}`,`원문: ${t.original}`,...Object.entries(t.answers).map(([k,v])=>`${k}: ${v}`),'예상 확인 항목',...t.checkItems,`엔지니어 메모: ${t.note}`].join('\n');const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`db-care-${t.id.slice(0,8)}.txt`;a.click();URL.revokeObjectURL(u)}
 return <dialog className="detail" ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="detail-inner"><header><div><div className="eyebrow">TICKET · {t.id.slice(0,8)}</div><h2>{t.customer}</h2><p>{t.category} · {t.code}</p></div><button autoFocus className="icon-button" onClick={onClose} aria-label="상세 닫기"><X/></button></header><div className="detail-body"><section className="summary-box"><span className="section-kicker">AI 상담 요약</span><h3>{t.category} · {t.code}</h3><p>{t.version}</p><dl><dt>고객사</dt><dd>{t.customer}</dd><dt>영향</dt><dd>{t.impact}</dd><dt>긴급도</dt><dd>{t.priority}</dd>{Object.entries(t.answers).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl></section><section><h3>고객 문의 원문</h3><blockquote>{t.original}</blockquote></section><section><h3>수집된 환경 정보</h3><dl><dt>DB Version</dt><dd>{t.version}</dd>{Object.entries(t.answers).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl></section><section><h3>예상 확인 항목</h3><ul className="check-list">{t.checkItems.map(c=><li key={c}><ClipboardCheck size={16}/>{c}</li>)}</ul><p className="disclaimer">※ AI 분석 결과는 참고 정보이며 최종 장애 판단 및 변경 작업은 DB 엔지니어가 수행합니다.</p></section><details><summary>AI 상담 내용 · {t.messages.length}개 메시지</summary><div className="transcript">{t.messages.map((m,i)=><p key={i}><strong>{m.role==='user'?'고객':'AI 상담원'}</strong>{m.text}</p>)}</div></details><section><h3>엔지니어 메모</h3><textarea aria-label="엔지니어 메모" rows="4" value={note} onChange={e=>{setNote(e.target.value);setSaved(false)}} placeholder="검토 결과와 다음 조치를 기록해주세요."/><button className="button secondary" onClick={()=>{onUpdate(t.id,{note});setSaved(true)}}>{saved?'저장되었습니다':'메모 저장'}</button></section><section><label>상태 변경<select value={t.status} onChange={e=>onUpdate(t.id,{status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></section></div><footer><span>자동 명령 실행 없음</span><button className="button secondary" onClick={download}><Download size={16}/>요약 다운로드</button></footer></div></dialog>
}

