import React,{useState,useEffect} from 'react';
import {Database,MessageSquare,LayoutDashboard,Info,ShieldCheck,RotateCcw,ArrowUpRight} from 'lucide-react';
import Consultation from './pages/Consultation.jsx';
import Dashboard from './pages/Dashboard.jsx';
import {loadTickets,saveTickets} from './utils/storage.js';
import {sampleTickets} from './data/sampleTickets.js';
import {PageTitle,Safety,Badge} from './components/UI.jsx';
import {oracleErrors} from './data/oracleErrors.js';
const initial=loadTickets();
export default function App(){const [page,setPage]=useState('dashboard'),[tickets,setTickets]=useState(initial.tickets),[notice,setNotice]=useState(initial.error||''),[resetKey,setResetKey]=useState(0);
 useEffect(()=>{const error=saveTickets(tickets);if(error)setNotice(error)},[tickets]);
 function reset(){if(window.confirm('이 브라우저의 상담 내역과 메모를 지우고 샘플 데이터로 초기화할까요?')){setTickets(sampleTickets());setResetKey(k=>k+1);setNotice('데모 데이터를 초기화했습니다.')}}
 const nav=[['consult','AI 상담',MessageSquare],['dashboard','문의 Dashboard',LayoutDashboard],['system','System Info',Info]];
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('dashboard')}}><div className="brand-icon"><Database size={23}/></div><div>DB Care <b>AI</b><small>INTELLIGENT DB SUPPORT</small></div></a><div className="nav-label">WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button key={key} onClick={()=>setPage(key)} className={page===key?'selected':''}><Icon size={18}/>{label}{key==='dashboard'&&<span className="nav-count">{tickets.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-box"><span className="demo-dot"/><strong>MVP Demo</strong><p>더 빠른 접수,<br/>더 명확한 기술지원.</p><span>Oracle Database Support</span></div><button className="reset-button" onClick={reset}><RotateCcw size={15}/>데모 데이터 초기화</button><div className="profile"><div>DE</div><span>DB Engineer<small>Support workspace</small></span><span className="online-dot"/></div></div></aside><main><header className="topbar"><span>Workspace <span className="slash">/</span><strong>AI DB Support Center</strong></span><div><span className="top-status"><i/>시스템 정상</span><span className="demo-tag">DEMO</span></div></header><div className="content">{notice&&<div className="global-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="안내 닫기">×</button></div>}<div hidden={page!=='consult'}><Consultation key={resetKey} onTicket={t=>{setTickets(prev=>[t,...prev]);setNotice('상담이 완료되어 문의 Dashboard에 등록되었습니다.')}} onDashboard={()=>setPage('dashboard')}/></div>{page==='dashboard'&&<Dashboard tickets={tickets} onUpdate={(id,changes)=>setTickets(prev=>prev.map(t=>t.id===id?{...t,...changes}:t))}/>} {page==='system'&&<><PageTitle eyebrow="SYSTEM INFORMATION" title="System Info" description="DB Care AI · AI 기반 DB 고객문의 1차 상담 시스템"/><section className="panel system-card"><Badge type="green">MVP v1.0</Badge><h2>기술지원의 첫 단계를 더 간결하게.</h2><p>고객의 데이터베이스 기술문의를 AI가 1차 접수하고, 장애 분석에 필요한 정보를 수집하여 DB 엔지니어에게 정리된 형태로 전달합니다.</p><div className="system-grid"><article><h3>Rule 기반 Mock AI</h3><p>오류 코드 및 키워드 분류와 순차 질문으로 동작합니다. 실제 LLM 분석은 수행하지 않습니다.</p></article><article><h3>브라우저 LocalStorage</h3><p>데이터는 현재 브라우저에만 저장됩니다. 기기·사용자 간 공유 또는 실제 엔지니어 알림은 제공하지 않습니다.</p></article><article><h3>음성 지원</h3><p>Web Speech API와 SpeechSynthesis를 사용합니다. 브라우저에 따라 외부 음성 인식 서비스 및 인터넷 연결이 필요할 수 있습니다.</p></article><article><h3>운영 DB 연결 없음</h3><p>명령 실행, 계정 변경, DB 시작·종료, 파일 변경 기능은 없습니다. 모든 변경 요청은 엔지니어 검토로 이관합니다.</p></article></div><h3>지원 Oracle 오류</h3><div className="error-grid">{Object.entries(oracleErrors).map(([code,r])=><div key={code}><code>{code}</code><span>{r.category}</span></div>)}</div></section><Safety/></>}<footer className="page-footer"><span>© {new Date().getFullYear()} DB Care AI</span><span>AI 기반 DB 고객문의 1차 상담 시스템</span><span>Built for better support <ArrowUpRight size={12}/></span></footer></div></main></div>
}

